# Use root/example as user/password credentials
version: '3.5'

services: 
  mongo:
    image: mongo
    container_name: myMongoDB
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hubert
      MONGO_INITDB_ROOT_PASSWORD: hubert@MONGODB

volumes:
  mongodb_data: